export const accessories = [    
    {
        id: 1,
        cat: "accessories",
        only:-1,
        name: "Apple AirPods Wireless ",
        image: "https://m.media-amazon.com/images/I/7120GgUKj3L._AC_UL320_.jpg",        
        description: "Apple AirPods (2nd Generation) Wireless Earbuds with Lightning Charging Case Included. Over 24 Hours of Battery Life, Effortless Setup. Bluetooth Headphones for iPhone",
        reviewsNum: 547475,
        globals:547519,
        stars: 4.8,
        price: -1,
        backPrice: -1,
        best: true,        
        allStars:[
            { num:"five", val:87 }, { num:"four", val:7 },{ num:"three", val:2 },
            { num:"two", val:1 }, { num:"one", val:2 }
        ],
        
        brand:[
            {name:"Brand", val:"Apple"},
            {name:"Model Name", val:"AirPods"},
            {name:"Color", val:"White"},
            {name:"Form Factor", val:"In Ear"},
            {name:"Connectivity Technology", val:"Bluetooth 5.0"}
        ],
        info:[
            {name: "Chip", val: "Apple H1 headphone chip"}, {name: "Hey Siri", val: "Always on"}, 
            {name: "Battery life (listening time on one charge)", val: "Up to 5 hours of listening time"}, {name: "LED Charging Light Location", val: "Top of Case"}, 
            {name: "Weight", val: "AirPods (each): 0.14 ounce (4 g), Charging Case: 1.34 ounces (38 g)"}, {name: "Dimensions", val: "AirPods (each): 0.65 by 0.71 by 1.59 inches (16.5 by 18.0 by 40.5 mm), Charging Case: 1.74 by 0.84 by 2.11 inches (44.3 by 21.3 by 53.5 mm)"}, 
            {name: "AirPods Sensors (each):", val: "Dual beamforming microphones, Dual optical sensors, Motion-detecting accelerometer, Speech-detecting accelerometer"}, {name: "Power and Battery", val: "AirPods with Charging Case: More than 24 hours listening time, up to 18 hours talk time; AirPods (single charge): Up to 5 hours listening time, up to 3 hours talk time or 15 minutes in the case equals up to 3 hours listening time or up to 2 hours talk time"}, 
        ],
        shipping: 0, 
        estimated: 0,
        dots: ["Quick access to Siri by saying “ Hey Siri ”", "More than 24 hours total listening time with the Charging Case", "Effortless setup, in-ear detection, and automatic switching for a magical experience", "Easily share audio between two sets of AirPods on your iPhone, iPad, iPod touch, or Apple TV"],
        note: false,
        largeImage: "https://m.media-amazon.com/images/I/7120GgUKj3L._AC_SX466_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/7120GgUKj3L.__AC_SY445_SX342_QL70_FMwebp_.jpg", 'https://m.media-amazon.com/images/I/71NLN1HgFkL._AC_SX466_.jpg', 'https://m.media-amazon.com/images/I/71NTi82uBEL._AC_SX466_.jpg', 'https://m.media-amazon.com/images/I/71QT9PrfxyL._AC_SX466_.jpg', 'https://m.media-amazon.com/images/I/81W5RSDOy-L._AC_SX466_.jpg'],
        safe: 0,
        stock:false,
        delivery:""

    },    
    {
        id: 2,
        cat: "accessories",
        only:0,
        name: "ZAGG InvisibleShield Screen Protector",
        image: "https://m.media-amazon.com/images/I/41iw6wCXrxS._AC_UL320_.jpg",
        description: "ZAGG InvisibleShield GlassFusion+ with D3O Screen Protector - Made Apple iPhone 12 mini - Case Friendly, clear (200307600)",
        reviewsNum: 46,
        globals:46,
        stars: 4.1,
        price: 45.96,
        backPrice: 49.99,
        best: false,        
        allStars:[
            { num:"five", val:61 }, { num:"four", val:20 },{ num:"three", val:3 },
            { num:"two", val:4 }, { num:"one", val:12 }
        ],
        brand:[
            {name:"Brand", val:"InvisibleShield"}, {name:"Compatible Devices", val:"Cellphone"},
            {name:"Material", val:"hybrid polymer, Plastic"}, {name:"Product Dimensions", val:"2.4\"L x 0.02\"W"},
            {name:"Compatible Phone Models", val:"Apple iPhone 12 mini"}, {name:"Finish Type", val:"Matte"},
            {name:"Unit Count", val:"1 Count"}, {name:"Screen Size", val:"5.4 Inches"},
            {name:"Screen Surface Description", val:"Glossy"}, {name:"Package Type", val:"Standard Packaging"}
        ],
        info:[
            {name: "Product Dimensions", val: "2.4 x 0.02 x 6.22 inches"},
            {name: "Item Weight", val: "0.176 ounces"}, 
            {name: "ASIN", val: "B08ZH55V7S"}, 
            {name: "Item model number", val: "200307600"}, 
            {name: "Other display features", val: "Wireless"}, 
            {name: "Form Factor", val: "Bumper"}, 
            {name: "Colour", val: "clear"}, 
            {name: "Included Components", val: "InvisibleShield, Cleaning wipe, Microfiber cloth, Dust removal sticker, Instructions, and EZ Apply Tray"}, 
        ],
        shipping: 41.28, 
        estimated: 48.63,
        dots: ["Elite Flexible Polymer with a Glass-like Feel: What is GlassFusion? We’ve developed an elite hybrid polymer that provides powerful, flexible protection with a glass-like feel. So, you get a transparent, smooth surface without the fragility of glass.", "Protected By D3O: D3O Is Broken Down To Its Most Raw Form And Engineered To Be Optically Clear. Then, We Integrate The D3O Material As The Final Layer Of Our Glassfusion Screen Protection. These Layers Are Fused Together To Make The Strongest Hybrid Polymer Screen Protection We’Ve Ever Made.", "Easy Application: We’Ve Made It Easy To Install Your Glassfusion+ With D3O By Providing Ez Apply Tabs And An Installation Tray, So You Get Perfect Alignment The First Time.", "Item Package Weight: 0.1543 Pounds"],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/41iw6wCXrxS._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/41iw6wCXrxS._AC_SX679_.jpg"],
        safe: 8,
        stock:true,
        delivery:"December 21 - January 4"

    },    
    {
        id: 3,
        cat: "accessories",
        only:1,
        name: "Stop & Talk Device Holder",
        image: "https://m.media-amazon.com/images/I/510eIwRBzoL._AC_UL320_.jpg",
        description: "Stop & Talk is a Device Holder and Door Stopper All in one! Heavy Duty Rubber Door Stopper or Handsfree use of Your iPhone or ipad. 122646",
        reviewsNum: 5,
        globals:5,
        stars: 5,
        price: 7.93,
        backPrice: 9.99,
        best: false,        
        allStars:[
            { num:"five", val:100 }, { num:"four", val:0 },{ num:"three", val:0 },
            { num:"two", val:0 }, { num:"one", val:0 }
        ],

        brand:[{name:"Brand", val:"Stop and Talk"}],
        info:[
            {name: "Manufacturer", val: "Stop and Talk"}, 
            {name: "Model", val: "Door Wedge / Cell Phone Holder"}, 
            {name: "Item Weight", val: "1.76 ounces"}, 
            {name: "Package Dimensions", val: "7.09 x 4.96 x 1.38 inches"}, 
            {name: "Country of Origin", val: "USA"}, 
            {name: "Item model number", val: "122646"}, 
            {name: "Manufacturer Part Number", val: "122646"}, 
            {name: "ASIN", val: "B0B7ZR4DGV"}, 
        ], 
        shipping: 41.73, 
        estimated: 24.22,
        dots: ["Stop and Talk is a device holder and a door stop all in one!", "Stop and Talk makes iphones and tablets (ipads) hands free and easy to use.", "When you need a door-stopper, simply place your Stop and Talk in front of a door and you have a functional adaptable door-stop.", "Stop and Talk is made from the highest quality, non-marking rubber. Most importantly, Stop & Talk is made right here in the USA!", "The Stop and Talk Door Stopper is Heavy Duty for years of use."],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/510eIwRBzoL._AC_SX425_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/510eIwRBzoL._AC_SX425_.jpg"],
        safe: 21,
        stock:true,
        delivery:"December 21 - January 3"
    },
    {
        id: 4,
        cat: "accessories",
        only:-1,
        name: "SAMSUNG EVO SD-Memory-Card",
        image: "https://m.media-amazon.com/images/I/71VXEYmRrZL._AC_UL320_.jpg",
        description: "SAMSUNG EVO Select Micro SD-Memory-Card + Adapter, 512GB microSDXC 130MB/s Full HD & 4K UHD, UHS-I, U3, A2, V30, Expanded Storage for Android Smartphones, Tablets, Nintendo-Switch (MB-ME512KA/AM)",
        reviewsNum: 38671,
        globals:38700,
        stars: 4.7,
        price: 44.98,
        backPrice: 84.99,
        best: false,        
        allStars:[
            { num:"five", val:84 }, { num:"four", val:10 },{ num:"three", val:3 },
            { num:"two", val:1 }, { num:"one", val:3 }
        ],

        brand:[
            {name:"Brand", val:"SAMSUNG"},
            {name:"Series", val:"EVO Select"},
            {name:"Flash Memory Type", val:"Micro SDXC"},
            {name:"Memory Storage Capacity", val:"256 GB"},
            {name:"Compatible Devices", val:"Tablet, Smartphone"}
        ],
        info:[
            {name: "Standing screen display size", val: "7 Inches"}, 
            {name: "RAM", val: "64 GB"}, 
            {name: "Hard Drive", val: "Solid State Drive"}, 
            {name: "Series", val: "EVO Select"}, 
            {name: "Item model number", val: "MB-ME256KA/AM"}, 
            {name: "Hardware Platform", val: "Nintendo Switch"}, 
            {name: "Item Weight", val: "0.317 ounces"}, 
            {name: "Flash Memory Size", val: "256"}, 
        ],
        shipping: 40.10, 
        estimated: 6.98,
        dots: ["ALL THE SPACE YOU NEED: Store lots of media on your phone with this micro SD memory card, load games on your Nintendo Switch and other devices, and download more apps on your tablet at top-notch speed.", "FAST AND SMOOTH: Superfast U3, class 10 rated transfer speeds of up to 130MB/s,and UHS-I Interface.", "EXPAND AND STORE BIG: The EVO Select card ranges from 64GB - 512GB, allowing you to record high-quality footage on your DJI drone, store it, and transfer it between devices."],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/71VXEYmRrZL._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/71VXEYmRrZL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71KSPJKOLiL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71gxoTnjx1L._AC_SY879_.jpg", "https://m.media-amazon.com/images/I/71t2BjdmLBL._AC_SX679_.jpg"],
        safe: 47,
        stock:true,
        delivery:"December 21 - January 3"
    },    
    {
        id: 5,
        cat: "accessories",
        only:4,
        name: "SOAR NCAA Protective Case",
        image: "https://m.media-amazon.com/images/I/71wQC-zXHgL._AC_UL1500_.jpg",
        description: "SOAR NCAA Protective Case for Airpods",
        reviewsNum: 37,
        globals:37,
        stars: 4.4,
        price: 17.36,
        backPrice: 0,
        best: false,        
        allStars:[
            { num:"five", val:74 }, { num:"four", val:8 },{ num:"three", val:8 },
            { num:"two", val:4 }, { num:"one", val:6 }
        ],

        brand:[
            {name:"Brand", val:"SOAR"},
            {name:"Color", val:"Team Color"},
            {name:"Form Factor", val:"Case"},
            {name:"Material", val:"Thermoplastic Polyurethane"},
            {name:"Special Feature", val:"Heavy Duty Protection"}
        ],
        info:[
            {name: "Item model number", val: "NCAA-APC2-IN"}, 
            {name: "Department", val: "unisex"}, 
            {name: "Date First Available", val: "November 29, 2022"}, 
            {name: "Manufacturer", val: "Prime Brands Group Inc."}, 
            {name: "ASIN", val: "B0BNKLZ5HK"}, 
            {name: "Best Sellers Rank", val: "#171,701 in Electronics "}
        ],
        shipping: 43.18, 
        estimated: 33.75,
        dots: ["Imported", "Protects your Apple Airpods from cracks and scratches", "Easy Access to charging Ports", "Perfect Snug Fit - Slides on and off with Ease", "Offical Licesned Product", "2 Cases Included!"],
        note: false,
        largeImage: "https://m.media-amazon.com/images/I/71wQC-zXHgL._AC_UL1500_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/71wQC-zXHgL._AC_UL1500_.jpg", "https://m.media-amazon.com/images/I/71uyruBCarL._AC_UL1500_.jpg", "https://m.media-amazon.com/images/I/91-6DD6nO5L._AC_UL1500_.jpg"],
        safe: 0,
        stock:true,
        delivery:"December 22 - 30"
    },        
    {
        id: 6,
        cat: "accessories",
        only:4,
        name: "Tile Mate Essentials (2022) Bluetooth Tracke",
        image: "https://m.media-amazon.com/images/I/51Z+YsjfUDL._AC_SX679_.jpg",
        description: "Tile Mate Essentials (2022) 4-Pack (2 Mate, 1 Slim, 1 Stickers)- Bluetooth Tracker & Item Locators for Keys, Wallets, Remotes & More; Easily Find All Your Things.",
        reviewsNum: 9194,
        globals:9194,
        stars: 4.6,
        price: 59.99,
        backPrice: 79.99,
        best: false,        
        allStars:[
            { num:"five", val:76 }, { num:"four", val:13 },{ num:"three", val:5 },
            { num:"two", val:2 }, { num:"one", val:4 }
        ],

        brand:[
            {name:"Brand", val:"Tile"},
            {name:"Are Batteries Included", val:"Yes"},
            {name:"Color", val:"Black"},
            {name:"Number of Batteries", val:"3 Lithium Metal batteries required. (included)"},
            {name:"Item Dimensions LxWxH", val:"3.36 x 2.12 x 0.1 inches"},
        ],
        info:[
            {name: "Product Dimensions", val: "3.36 x 2.12 x 0.1 inches"}, 
            {name: "Item Weight", val: "2.1 ounces"}, 
            {name: "ASIN", val: "B09B2YYD7W"}, 
            {name: "Item model number", val: "RE-47004"}, 
            {name: "Batteries", val: "3 Lithium Metal batteries required. (included)"}, 
            {name: "Best Sellers Rank", val: "#90 in Electronics "}, 
            {name: "Connectivity technologies", val: "Bluetooth"}, 
            {name: "Other display features", val: "CE"}, 
            {name: "Device interface - primary", val: "Buttons"}, 
            {name: "Colour", val: "Black"}, 
            {name: "Included Components", val: "2 Tile Mate, 1 Tile Slim and 1 Tile Sticker"}, 
        ],
        shipping: 40.65, 
        estimated: 35.24,
        dots: ["A VARIETY OF TRACKERS FOR YOUR THINGS - A selection of Tiles to help keep track of your keys, wallet, remotes and more. Keep track of more for less with our multi-packs or give them to your friends and family as a gift.", "FIND NEARBY - Use the Tile app to ring your Tile when it’s within Bluetooth range, or ask your Smart Home device to find it for you.", "FIND FAR AWAY - When outside of Bluetooth range, use the Tile app to view your Tile’s most recent location on a map", "FIND YOUR PHONE - Double press the button on your Tile to make your phone ring, even when it’s on silent.", "NOTIFY WHEN FOUND - Enlist the secure and anonymous help of the Tile Network to help find your things. If your lost Tile is found, If your Tile is lost, add your contact information so you can be reached when someone scans the QR code on your lost Tile.", "ANDROID, IOS & SMART HOME COMPATIBLE - Find your things with the free Tile app on both iOS and Android devices. Tile also works with Amazon Alexa, Hey Google and Siri", "TECH SPECS - Water-Resistant (IP67 rated), Up to 3-year non-replaceable battery, Up to 250 ft / 76 m Bluetooth range"],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/51Z+YsjfUDL._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/51Z+YsjfUDL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61pbHoYrGXL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61Tm6D4dPHL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71zXF1s1OOL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61dfxUXno8L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61dfxUXno8L._AC_SX679_.jpg"],
        safe: 25,
        stock:true,
        delivery:" December 30 - January 17"
    },
    {
        id: 7,
        cat: "accessories",
        only:0,
        name: "SanDisk 128GB Memory Card",
        image: "https://m.media-amazon.com/images/I/81wwLOgkLgL._AC_SX679_.jpg",
        description: "SanDisk 128GB Extreme PRO SDXC UHS-I Memory Card - C10, U3, V30, 4K UHD, SD Card - SDSDXXD-128G-GN4IN",
        reviewsNum: 4291,
        globals:4290,
        stars: 4.8,
        price: 24.75,
        backPrice: 33.49,
        best: true,        
        allStars:[
            { num:"five", val:88 }, { num:"four", val:8 },{ num:"three", val:2 },
            { num:"two", val:0 }, { num:"one", val:1 }
        ],

        brand:[
            {name:"Brand", val:"SanDisk"},
            {name:"Series", val:"SanDisk Extreme PRO SD UHS-I Card"},
            {name:"Flash Memory Type", val:"SDXC"},
            {name:"Memory Storage Capacity", val:"128 GB"},
            {name:"Compatible Devices", val:"Computers, Digital Cameras, Home Theatre Devices, Car Navigation Systems"},
        ],
        info:[
            {name:"Brand", val:"SanDisk"},
            {name: "Series", val: "SanDisk Extreme PRO SD UHS-I Card"}, 
            {name: "Item model number", val: "SDSDXXD-128G-GN4IN"}, 
            {name: "Item Weight", val: "0.071 ounces"}, 
            {name: "Product Dimensions", val: "0.09 x 0.94 x 1.26 inches"}, 
            {name: "Item Dimensions LxWxH", val: "0.09 x 0.94 x 1.26 inches"}, 
            {name: "Color", val: "Dark gray/Black"}, 
            {name: "Batteries", val: "1 Lithium Ion batteries required."}, 
            {name: "Manufacturer", val: "Western Digital Technologies, Inc."}, 
            {name: "Language", val: "English"}, 
            {name: "ASIN", val: "B09X7FXHVJ"}, 
        ],
        shipping: 40.48, 
        estimated: 5.36,
        dots: ["Save time with card offload speeds of up to 200MB/s powered by SanDisk QuickFlow Technology (Up to 200MB/s read speeds, engineered with proprietary technology to reach speeds beyond UHS-I 104MB/s, require compatible devices capable of reaching such speeds. Based on internal testing; performance may be lower depending upon host device, interface, usage conditions and other factors. 1MB=1,000,000 bytes. X = 150KB/sec. SanDisk QuickFlow Technology is only available for 64GB, 128GB, 256GB, 512GB and 1TB capacities. 1GB=1,000,000,000 bytes. 1TB=1,000,000,000,000 bytes. Actual user storage less.)", "Pair with the SanDisk Professional PRO-READER SD and microSD to achieve maximum speeds (sold separately)", "Shot speeds up to 90MB/s (Write speed up to 90MB/s. Based on internal testing; performance may be lower depending upon host device. 1MB=1,000,000 bytes. X = 150KB/sec.)", "Perfect for shooting 4K UHD video and sequential burst mode photography (Full HD (1920x1080) and 4K UHD (3840 x 2160) video support may vary based upon host device, file attributes and other factors. See HD page on SanDisk site.)", "UHS Speed Class 3 (U3) and Video Speed Class 30 (V30) (UHS Speed Class 3 designates a performance option designed to support 4K UHD video recording with enabled UHS host devices. UHS Video Speed Class 30 (V30), sustained video capture rate of 30MB/s, designates a performance option designed to support real-time video recording with UHS enabled host devices. See the SD Association’s official website.)"],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/81wwLOgkLgL._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/81wwLOgkLgL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/811SwFsGiFL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/91mlqzCSaJL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/914qgzBVciL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/81HW2adIgtL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/81h7MHVbUaL._AC_SX679_.jpg"],
        safe: 26,
        stock:true,
        delivery:"December 22 - January 5"
    },
    {
        id: 8,
        cat: "accessories",
        only:0,
        name: "Belkin Power Strip Surge Protector",
        image: "https://m.media-amazon.com/images/I/61B50z1-b7L._AC_SY879_.jpg",
        description: "Belkin Power Strip Surge Protector - 12 AC Multiple Outlets & 8 ft Long Flat Plug Heavy Duty Extension Cord for Home, Office, Travel, Computer Desktop, Laptop & Phone Charging Brick (3,940 Joules)",
        reviewsNum: 48801,
        globals:48801,
        stars: 4.8,
        price: 27.99,
        backPrice: 0,
        best: false,        
        allStars:[
            { num:"five", val:86 }, { num:"four", val:10 },{ num:"three", val:2 },
            { num:"two", val:0 }, { num:"one", val:1 }
        ],

        brand:[
            {name:"Brand", val:"Belkin"},
            {name:"Color", val:"Gray"},
            {name:"Total Power Outlets", val:"12"},
            {name:"Voltage", val:"125 volts"},
            {name:"Item Dimensions LxWxH", val:"6.1 x 2.1 x 15.6 inches"}
        ],
        info:[
            {name:"Product Dimensions", val:"6.1 x 2.1 x 15.6 inches"},
            {name:"Item Weight", val:"2 pounds"},
            {name:"ASIN", val:"B000J2EN4S"},
            {name:"Item model number", val:"BE112230-08"},
            {name:"Best Sellers Rank", val:"#246 in Electronics"},
            {name:"Is Discontinued By Manufacturer", val:"No"},
            {name:"Date First Available", val:"October 2, 2001"},
            {name:"Manufacturer", val:"Belkin Components"},
            {name:"Language", val:"English"},
        ],
        shipping: 50.32, 
        estimated: 24.29 ,
        dots: ["Multi-Outlet Surge Protector Power Strip: Power everything on your desk with a single compact surge-protected extension cord. This reputable power cord offers 12 AC outlets with surge protector for charging your computer, laptop, phone, camera, and more. One charging station for a clutter-free desk.", "Power Bar with Phone Line Protection: Featuring a 1-in-2-out RJ11 telephone or fax protection to ensure open and continuous phone line connections. It also provides a coaxial cable protection to safeguard cable box and satellite connections. The damage-resistant housing protects circuits from fire, impact, and rust.", "Safeguard Your Devices and Appliances: The electric strip has a 3,940-Joule energy rating providing a reliable power extension cord to protect printers, broadband modems, or home theater systems. It secures your electronic devices from overload, short circuit, power spikes, lightning strikes, or fluctuations.", "Compact, Heavy Duty, and Space-Saving: The widely spaced outlets give ample area to fit big plugs and charger bricks. Its slender design makes it ideal for home office, workstations, and game rooms. The durable cord is 8 ft / 2.4 meters long with a 3-prong angle plug convenient for tight spaces.", "Reliable Product and Service: Purchase with confidence as it is backed by a limited lifetime warranty and protected by a dollar 200,000 Connected Equipment Warranty. Check out the full specs: 6,000 volts maximum spike voltage, 15A AC, 125V, and 1875W. Each outlet has a safety slide lock to close unused sockets safeguarding you and your kids."],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/61B50z1-b7L._AC_SY879_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/61B50z1-b7L._AC_SY879_.jpg", "https://m.media-amazon.com/images/I/51Tuq71F9iL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/51wYUKOx3XL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/71YPtlO0THL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/91MWQXVveuL._AC_SX425_.jpg"],
        safe: 0,
        stock:true,
        delivery:"December 22 - January 5"
    },    
    {
        id: 9,
        cat: "accessories",
        only:0,
        name: "BlueParrott B450-XT Noise Cancelling Bluetooth Headset",
        image: "https://m.media-amazon.com/images/I/71LoB8S53DL._AC_SX679_.jpg",
        description: "BlueParrott B450-XT Noise Cancelling Bluetooth Headset – Updated Design with Industry Leading Sound & Improved Comfort, Up to 24 Hours of Talk Time, IP54-Rated Wireless Headset,Black",
        reviewsNum: 14639,
        globals:14639,
        stars: 4.2,
        price: 129.99,
        backPrice: 169.99,
        best: true,        
        allStars:[
            { num:"five", val:68 }, { num:"four", val:12 },{ num:"three", val:7 },
            { num:"two", val:4 }, { num:"one", val:9 }
        ],

        brand:[
            {name:"Brand", val:"BlueParrott"},
            {name:"Model Name", val:"B450-XT"},
            {name:"Color", val:"Black"},
            {name:"Form Factor", val:"On Ear"},
            {name:"Connectivity Technology", val:"Bluetooth"}
        ],
        info:[
            {name:"Product Dimensions", val:"3.6 x 1.1 x 0.63 inches"},
            {name:"Item Weight", val:"0.9 ounces"},
            {name:"ASIN", val:"B087R97MM2"},
            {name:"Item model number", val:"204270"},
            {name:"Batteries", val:"1 Lithium Ion batteries required. (included)"},
            {name:"Best Sellers Rank", val:"#1 in Telephone Headsets"},
            {name:"Wireless communication technologies", val:"Bluetooth"},
            {name:"Connectivity technologies", val:"Bluetooth"},
            {name:"Special Features", val:"Wireless, Noise Cancellation, Lightweight, Microphone Included"},
            {name:"Other display features", val:"Wireless"},
            {name:"Audio Jack", val:"Bluetooth"},
            {name:"Included Components", val:"1x BlueParrott B450-XT headset, 1x USB charging cable, 1x foam ear cushion, 1x microphone windscreen, Quick Start Guide, Warranty and Warning Leaflet, mobile charger"},
        ],
        shipping: 45.01, 
        estimated: 65.09,
        dots: ["INDUSTRY-LEADING NOISE CANCELLATION – Upgraded to keep pace with the demands of life on the go, BlueParrott B450-XT blocks out 96% of background noise so you can hear and be heard clearly wherever you are.Connector Type:Bluetoot", "IMPROVED WIRELESS RANGE – Upgraded to Bluetooth 5.0 for better connectivity, this hands-free headset features a long wireless range of 300 feet/100 meters Plus, with VoiceControl, you can answer or reject calls with just your voice", "PREMIUM COMFORT – With a padded headband & large, cushioned earcups, BlueParrott B450-XT is built for improved comfort for all-day use Plus, with up to 24 hours of talk time on a single charge & USB-C charging, it’s easier than ever to stay connected", "ULTRA-DURABLE DESIGN – Tough enough for life on the go with IP54-rated protection against dust and moisture, this is the ideal wireless headset for truck drivers, field services, retail, hospitality, and warehouse workers", "EASY CUSTOMIZATION – The BlueParrott App provides easy firmware upgrades and feature selection, with no need to connect to a computer Plus, the customizable BlueParrott Button enables fast access to your favorite features such as mute, speed dial, and more"],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/71LoB8S53DL._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/71LoB8S53DL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/611b4B2fS+L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61IrNQzdwQL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/716nHvV02-L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71ksRStuynL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71uXf565jiL._AC_SX679_.jpg"],
        safe: 24,
        stock:true,
        delivery:"December 22 - January 6"
    },        
    {
        id: 10,
        cat: "accessories",
        only:0,
        name: "PopSockets: Phone Grip",
        image: "https://m.media-amazon.com/images/I/61vnoHP4AcL._AC_SX679_.jpg",
        description: "PopSockets: Phone Grip for MagSafe, Phone Holder, Wireless Charging Compatible - Clear",
        reviewsNum: 8450,
        globals:8450,
        stars: 4.5,
        price: 29.99,
        backPrice: 0,
        best: false,        
        allStars:[
            { num:"five", val:78 }, { num:"four", val:10 },{ num:"three", val:5 },
            { num:"two", val:3 }, { num:"one", val:5 }
        ],

        brand:[
            {name:"Brand", val:"PopSockets"},
            {name:"Color", val:"Clear"},
            {name:"Material", val:"Polycarbonate"},
            {name:"Installation Type", val:"Magnetic Mount"},
            {name:"Mounting Type", val:"Magnetic"},
        ],
        info:[
            {name:"Package Dimensions", val:"5.55 x 2.99 x 0.83 inches"},
            {name:"Item Weight", val:"1.62 ounces"},
            {name:"ASIN", val:"B0BFJVN371"},
            {name:"Item model number", val:"806226"},
            {name:"Best Sellers Rank", val:"#116 in Cell Phones & Accessories"},
            {name:"Other display features", val:"Wireless"},
            {name:"Colour", val:"Clear"},
            {name:"Included Components", val:"PopGrip Magsafe"},
            {name:"Manufacturer", val:"PopSockets"},
            {name:"Date First Available", val:"September 16, 2022"}
        ],
        shipping: 40.50, 
        estimated: 17.10,
        dots: ["Our phone grip for MagSafe we call a \"PopGrip\" securely attaches to your MagSafe-compatible case for maximum grip and kickstand capabilities", "Wirelessly charge your iPhone by simply sliding off the magnetic PopSocket and setting on a wireless charging pad", "Offers a secure grip so you can text with one hand, avoid phone drops, and use as a phone stand on-the-go", "Pop Grip for MagSafe is compatible with PopSocket cases and mounts for MagSafe and non-PopSocket cases for MagSafe", "Strong built-in magnets securely attach the cell phone holder grip to MagSafe-compatible cases"],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/61vnoHP4AcL._AC_SX679_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/61vnoHP4AcL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71prVN6nZFL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/61DmcRl6Q2L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71i-eixKO0L._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71kgd7acNcL._AC_SX679_.jpg", "https://m.media-amazon.com/images/I/71KdUiZBWYL._AC_SX679_.jpg"],
        safe: 0,
        stock:true,
        delivery:"December 22 - January 9"
    },            
    {
        id: 11,
        cat: "accessories",
        only:0,
        name: "Skullcandy Hesh Evo Wireless Bluetooth Headphones",
        image: "https://m.media-amazon.com/images/I/81C7IY23niL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
        description: "Skullcandy Hesh Evo Wireless Over-Ear Bluetooth Headphones for iPhone and Android with Mic / 36 Hour Battery Life / Great for Music, School, Workouts, and Gaming / Compact Travel Design - Black",
        reviewsNum: 348,
        globals:3448,
        stars: 4.6,
        price: 79.99,
        backPrice: 104.99,
        best: false,        
        allStars:[
            { num:"five", val:75 }, { num:"four", val:15 },{ num:"three", val:5 },
            { num:"two", val:2 }, { num:"one", val:3 }
        ],

        brand:[
            {name:"Brand", val:"Skullcandy"},
            {name:"Model Name", val:"Hesh Evo"},
            {name:"Color", val:"True Black"},
            {name:"Form Factor", val:"  Over Ear"},
            {name:"Connectivity Technology", val:"Bluetooth 5.0"},
        ],
        info:[
            {name:"Battery Life", val:"Up to 36 Hours"},
            {name:"Rapid Charge", val:"10 Minutes = 3 Hours"},
            {name:"Controls", val:"Call, Track and Volume"},
            {name:"Charging Cable", val:"USB-C"},
            {name:"Brand", val:"Skullcandy"},
            {name:"Model Name", val:"Hesh Evo"},
        ],
        shipping: 46.57, 
        estimated: 44.31,
        dots: ["Supreme Audio - With powerful 40mm drivers and exceptional acoustics your favorite tunes will be crystal clear. For the affordable price of the Hesh Evo it reigns over the competition and provides the best sound quality in class.", "36 hours battery - Whether you're on the road and can't charge or you're on a 36 hour gaming session the Hesh Evo will have your back. Plus, use rapid charge and a quick 10 minute charge will give you 3 hours of listening.", "Sick Fit - Ames writes 'cushiony and plush. Has nice squish at the top of the headpiece and there's a lot of cushioning where it goes over your ears' We couldn't have said it better! Don't forget the soft headband and noise isolating design.", "Never lost with Tile - With Tile tech, Skullcandy makes it super easy to track down either headphones and keep your gadgets safe! Download the Tile app and follow the instructions to activate.", "Buy With Confidence - 1 Year manufacture warranty included with the Hesh Evo, be sure to wear your headphones with full confidence."],
        note: true,
        largeImage: "https://m.media-amazon.com/images/I/81C7IY23niL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
        moreImages: ["https://m.media-amazon.com/images/I/81C7IY23niL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "https://m.media-amazon.com/images/I/81wteQjuHPL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/71-H8cgwl+L._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/91RkAR9tfVL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/81MbAOrGQLL._AC_SX425_.jpg", "https://m.media-amazon.com/images/I/71U3f5T6sGL._AC_SX425_.jpg"],
        safe: 24,
        stock:true,
        delivery:"December 28 - January 4"
    },                
]


