export const reviewsAM = [
    {
        "id":1,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"I Feel Fine",
        "date" :"Reviewed in the United States 🇺🇸 on December 9, 2022",
        "verified" :true,
        "comment" :"A lot of people are asking if these are Generation 2. Here's what I found.<br>The box itself reads \"Model A2032 A2031 A1602\". ... verbatim on the packaging... if you want to look up the details yourself.<br>The package includes A2032 and A2031 left and right AirPods. Apple calls both 2nd generation. And the package also includes a A1602 case. Apple calls this Lightning Charging Case with no specific mention of generation.<br>From what I can see, Apple never quite calls the included Lightning Charging Case a gen 1 product but lots of other sellers do. Some of the confusion is born here.",
        "helpful" :10
    },
    {
        "id":2,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"Duggo",
        "date" :"Reviewed in the United States 🇺🇸 on December 12, 2022",
        "verified" :true,
        "comment" :"Yes, I\'m an Apple fanboy my whole life. When these wireless headphones came out and everyone (including tech writers) was making fun of them, I bought them immediately and now wear them almost constantly. I have \"read\" countless audio books I would never have gotten to and I now own AirPods Pro also, for mowing lawns, etc. for the noice canceling capabilities. I had a pair of bluetooth headphones previously, but they were so much trouble to pair and use that I abandoned them after a month or so. Leave it to Apple to make a product so easy to use!",
        "helpful" :2
    },
    {
        "id":3,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"Clarissa",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"We love our Apple AirPods! Our family of four each have a pair. We’ve sampled other brands, but all agree this product is the best overall in all categories.<br>The 2nd generation has noticeable improvements in sound quality and battery life, which we rate 5/5 stars in both categories.<br>We rate noise cancellation at 3/5, but we feel it’s safer to be able to hear the outside environment at a small degree. (Check out AirPods Pro if you’re looking for total noise cancellation).<br>Overall, we rate Apple AirPods 5/5",
        "helpful" :2
    },
    {
        "id":4,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"James M.",
        "date" :"Reviewed in the United States 🇺🇸 on January 7, 2020",
        "verified" :true,
        "comment" :"Taking the Apple AirPods at face value, they're a solid headset for the money! If you already have the original, first generation AirPods and just want to upgrade, not a bad option either. The 2nd generation AirPods feature an improved software chip & runs off of BlueTooth 5.0 vs 4.1 (Gen 1). The software chip allows a faster, stronger, and more stable connection with your device(s). This particular item for $139.00 does NOT feature the wireless charging case. This one must be plugged in via USB (cable provided in the box) to an outlet or USB port. The wireless charging case model is $169. Now if you're looking to upgrade to the wireless charging case later on, you can. Apple does sell it separately. If you want the wireless charging option right out of the box, I recommend sending the $169 vs the $139 product here.",
        "helpful" :556
    },
    {
        "id":5,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"Alexa Gaines",
        "date" :"Reviewed in the United States 🇺🇸 on December 14, 2022",
        "verified" :true,
        "comment" :"Was a gift for my fiancé who kept stealing my AirPods. Definitely worth it! I love AirPods. These are the only style headphones that don’t bother my ears. I wish they made more of these types. They work well and last pretty long on case charge. I’ve had mine for about 2 years now and they still work great. Glad to have them back to myself now!",
        "helpful" :1
    },
    {
        "id":6,
        "forID": 1,
        "cat": "accessories",
        "image" :"",
        "name" :"Lourdes",
        "date" :"Reviewed in the United States 🇺🇸 on December 2, 2022",
        "verified" :true,
        "comment" :"I decided to finally buy these on Black Friday after watching them for the longest time. I am so glad I did! The sound quality, features and comfort are top notch. They fit comfortably and do not fall off even when bending down, running or laying down. Battery life is great because the case stays charged for more than 24 hours. My case has stayed charged going on two days and I fully charged the pods three times during this time. Noise cancellation is not great but I can still listen comfortably to a podcast while driving on the highway with a window open. I couldn’t do that with the wired Apple headphones. Music sounds great. Equivalent to the wired headphones. You won’t regret getting these.",
        "helpful" :22
    },


    {
        "id":7,
        "forID": 2,
        "cat": "accessories",
        "image" :"",
        "name" :"Kari",
        "date" :"Reviewed in the United States 🇺🇸 on March 31, 2022",
        "verified" :true,
        "comment" :"I had so many issues with tempered glass screen protectors cracking after a small fall. Enough the expensive name brand ones. I was looking for a non glass HD screen protector and took my chance on this one! So glad I found it. Though it does scratch easy it’s better than cracked screen protectors. Until I find something that doesn’t crack and doesn’t scratch easy I’ll probably continue to use this one. I wish zagg still made the plastic screen protectors you could apply with liquid that wouldn’t scratch or crack.",
        "helpful" :1
    },
    {
        "id":8,
        "forID": 2,
        "cat": "accessories",
        "image" :"",
        "name" :"Skip K",
        "date" :"Reviewed in the United States 🇺🇸 on November 11, 2021",
        "verified" :true,
        "comment" :"Been using these for years on multiple iPhones. I use them in addition to a case with a screen protector for 2 layers of protection. What separates these from others is the way it adheres to the phone screen and is pliable not rigid…not only providing scratch protection but adds strength and integrity to the phone screen. Only reason it doesn’t get 5 stars is it’s a tad bit tricky to install",
        "helpful" :0
    },
    {
        "id":9,
        "forID": 2,
        "cat": "accessories",
        "image" :"",
        "name" :"Tyla Richard",
        "date" :"Reviewed in the United States 🇺🇸 on July 27, 2022",
        "verified" :true,
        "comment" :"The installation was easier than I thought it would be. It completely disappears on the phone. Very satisfied with this purchase.",
        "helpful" :2
    },
    {
        "id":10,
        "forID": 2,
        "cat": "accessories",
        "image" :"",
        "name" :"SlushieKen",
        "date" :"Reviewed in the United States 🇺🇸 on June 10, 2021",
        "verified" :true,
        "comment" :"If your considering this screen cover and you can afford it - this is your very best option. This thing works super good. It could be tougher than the screen itself from my experience.<br>Be aware you only get 1 in the package.<br>If you get bubbles just let it stay warm in your pocket a few days and they will come out on their own (no need to over scrape to push them out or you risk damage)",
        "helpful" :7
    },
    {
        "id":11,
        "forID": 2,
        "cat": "accessories",
        "image" :"",
        "name" :"Theodore R Hardman",
        "date" :"Reviewed in the United States 🇺🇸 on May 28, 2022",
        "verified" :true,
        "comment" :"Loved the tool to hold the screen and center it onto the phone. A couple of bubbles at first but they went away on their own after a day or two.",
        "helpful" :0
    },
    {
        "id":12,
        "forID": 3,
        "cat": "accessories",
        "image" :"",
        "name" :"Jim Bassett",
        "date" :"Reviewed in the United States 🇺🇸 on October 24, 2022",
        "verified" :true,
        "comment" :"I searched but couldn't find it on Amazon. A friend had to give me the name of the product to find it. It's the most practical, inexpensive product I've purchased in a long time. Bought it for a door stop and I ended up using it more to hold my iPhone and tablet. Also use it in my car and golf cart (just wedge it under the window).",
        "helpful" :0
    },
    {
        "id":13,
        "forID": 3,
        "cat": "accessories",
        "image" :"",
        "name" :"Clark Ashworth",
        "date" :"Reviewed in the United States 🇺🇸 on October 16, 2022",
        "verified" :true,
        "comment" :"Very “handy” item. I do a lot of Team’s/Zoom meetings and the Stop & Talk let’s me participate in these meetings while also allowing me to utilize my hands for taking notes or using my keyboard. All for &lt; than $10.",
        "helpful" :0
    },
    {
        "id":14,
        "forID": 3,
        "cat": "accessories",
        "image" :"",
        "name" :"albert murphy",
        "date" :"Reviewed in the United States 🇺🇸 on October 28, 2022",
        "verified" :true,
        "comment" :"I have one in the office and one at home. Perfect angles to read, watch videos, zoom, etc. with my phone. Very useful and inexpensive.",
        "helpful" :0
    },
    {
        "id":15,
        "forID": 3,
        "cat": "accessories",
        "image" :"",
        "name" :"Todd Downing",
        "date" :"Reviewed in the United States 🇺🇸 on October 14, 2022",
        "verified" :true,
        "comment" :"I bought this cleaver, affordable, and very functional device holder. Because it's small and portable, I take it with me in my briefcase. I plan to buy 20 for my office. Thanks.",
        "helpful" :0
    },
    {
        "id":16,
        "forID": 3,
        "cat": "accessories",
        "image" :"",
        "name" :"tim",
        "date" :"Reviewed in the United States 🇺🇸 on October 14, 2022",
        "verified" :true,
        "comment" :"I thought looking for a door stopper for my office was a straight forward task. Boy was I surprised when I found the stop and talk! Obviously I had to buy multiple. I love that I can have a phone holder on my desk. It makes facetime calls on my iphone a breeze. Will be getting more for stocking stuffers this year!",
        "helpful" :0
    },
    {
        "id":17,
        "forID": 4,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/2b6ca751-c12a-4105-ba5d-e062837feb37._CR110,0,280,280_SX48_.jpg",
        "name" :"BMO",
        "date" :"Reviewed in the United States 🇺🇸 on December 13, 2022",
        "verified" :true,
        "comment" :"It’s awesome how affordable these cards are now, I got this one for less than $50 after tax during the pre-Black Friday sale. I remember when the Nintendo Switch came out at half this much storage was over twice the price. I picked this one because it’s a little faster than the U1 speeds, as well as being A2 certified. I’m specifically using it for Steam Deck games (which are technically applications). A2 means it will work better with apps/games because of higher random read/write performance. The blue color is pretty also, better than the old green color that Samsung used to use. If you’re on the fence about using Micro SD cards for Steam Deck or Nintendo Switch, just know that the load times are almost as fast as internal flash storage.",
        "helpful" :6
    },
    {
        "id":18,
        "forID": 4,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/1a150ee4-a154-4154-a2cf-75be43f6ae8b._CR87,0,225,225_SX48_.jpg",
        "name" :"Jeremy",
        "date" :"Reviewed in the United States 🇺🇸 on December 11, 2022",
        "verified" :true,
        "comment" :"I was running out of space of only having 3.7GB who knew that 64GB is not enough for games these days. I only have a few games installed. I only buy games on sale and never knew it would fill up the 64gb that fast. 256GB is enough since I dont play my Switch enough. I prefer to buy the cartridge games if they are worth it. This was a good deal and I needed the extra space for my Switch because even DLC is huge for Smash Bros Ultimate and Dragon Ball Z Fighters has ton of DLC that can max out the 64gb hard drive space.",
        "helpful" :0
    },
    {
        "id":19,
        "forID": 4,
        "cat": "accessories",
        "image" :"",
        "name" :"Amazon Customer",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"I got a 64gb Steamdeck, and understandably, needed some extra storage. This did the job perfectly. You'd think that vs a beefier steamdeck with an NVME SSD, that a microSD would cause horrendous slowdowns. I'm here to tell you thats not the case. All of my games loaded perfectly fine. I tested Doom Eternal ,Devil May Cry 5 and Elden Ring, on top of many other games and this card works like a charm, loads everything fast with no slowdowns in game. Don't let it discourage you.",
        "helpful" :1
    },
    {
        "id":20,
        "forID": 4,
        "cat": "accessories",
        "image" :"",
        "name" :"Demetrius Alize",
        "date" :"Reviewed in the United States 🇺🇸 on December 14, 2022",
        "verified" :true,
        "comment" :"I'm pretty happy with this purchase it works it doesn't have the full storage capacity but anybody in the engineering field knows that memory cards don't fully come with the storage capacity because there's other things installed on those memory cards so I believe it came with like 120/111 GB still I got what I paid for I'm pretty happy plus it was on sale.",
        "helpful" :1
    },
    {
        "id":21,
        "forID": 4,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/5f8cb11f-be70-455c-a214-ab7b7b5b9d3e._CR62,0,375,375_SX48_.jpg",
        "name" :"David Washburn",
        "date" :"Reviewed in the United States 🇺🇸 on December 13, 2022",
        "verified" :true,
        "comment" :"Bought this and installed in a Rove R2-4K dash cam. Lasted just under a year until it started having problems. Now it is completely dead. Not sure it is the product’s problem more than it is the situation of being in the hot/cold windshield installed in a dash cam. Just wanted to communicate this issue. I’ve contacted Rove and still await a response.",
        "helpful" :2
    },
    {
        "id":22,
        "forID": 4,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/f0432f0f-240c-4670-9592-7a09109e5cdf._CR0,148.0,704,704_SX48_.jpg",
        "name" :"Tony aka KettleBlackArtsAnd",
        "date" :"Reviewed in the United States 🇺🇸 on December 2, 2022",
        "verified" :true,
        "comment" :"Have not had any issues using this for my GoPro or my iPad. I've only had one device give me issues. So I don't use this card in that device. But it works for my other ones just fine. Keep an eye on the prices they do fluctuate and you can get these at a good deal. Just like the 256 gigs for 25 bucks or less you're doing good. But I have not had an issue with 128 gig or the 256 gig other than the one item. But that device is finicky anyways. We all have one of those items that doesn't always work like it should. Hope this helps and you have a good one",
        "helpful" :2
    },
    {
        "id":23,
        "forID": 5,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/86fb4278-cfb3-4b67-bef5-77018ee5c3c7._CR0,26.0,281,281_SX48_.jpg",
        "name" :"Serenity",
        "date" :"Reviewed in the United States 🇺🇸 on January 8, 2021",
        "verified" :true,
        "comment" :"The tops are a bit larger than the airpod too but I solved that by using a hair dryer on high heat to shrink it to fit. Otherwise it made a great gift.",
        "helpful" :0
    },
    {
        "id":24,
        "forID": 5,
        "cat": "accessories",
        "image" :"",
        "name" :"Teddi M",
        "date" :"Reviewed in the United States 🇺🇸 on October 31, 2022",
        "verified" :true,
        "comment" :"These are very cute for games and Duck fans. The material is harder plastic, not silicone and the lid is not attached, making it 2 pieces. We have lost (and found) the tops several times already. Would not buy again, not for everyday use.",
        "helpful" :0
    },
    {
        "id":25,
        "forID": 5,
        "cat": "accessories",
        "image" :"",
        "name" :"lylly jenkins",
        "date" :"Reviewed in the United States 🇺🇸 on August 24, 2020",
        "verified" :true,
        "comment" :"Not at all like the picture the Georgia G is extremely small and the top of the case and the bottom are not connected so the top slides off everytime you open them",
        "helpful" :0
    },
    {
        "id":26,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"j money",
        "date" :"Reviewed in the United States 🇺🇸 on December 1, 2022",
        "verified" :true,
        "comment" :"I like everything that this product offers to begin with. But I really dislike the subscription demands. Many other competitors add free proximity sensing alarm aka anti forget alarm aka walking away accident protection. I have this card and a airbolt wallet Bluetooth tracker that has the proximity alarm I can just use that feature separately from this card so I don't gave to pay for it. The Bluetooth reconnecting on this device is phenomenal compared to my other Bluetooth tracker. The GPS finding feature is pretty good. Many people around me over 400 to 500 people also had tile devices that could help me spot my missing card if I lost it nearby. Subscription fees makes me not give this product a perfect score of 5 out of 5 scale. I'd recommend people to buy this and another competitor product to use free features from the other ones.",
        "helpful" :19
    },
    {
        "id":27,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"Garrett",
        "date" :"Reviewed in the United States 🇺🇸 on September 16, 2022",
        "verified" :true,
        "comment" :"I never really lose my wallet but if I did I’d be pretty unhappy. I use a bifold leather wallet made by Duvall leatherworks in Pennsylvania (for size reference If you want). It fits nicely inside the innermost pocket. It honestly doesn’t make the wallet feel bulky or anything.<br>When I first got the device I saw the button that you use to interact with your phone for connecting it and also using it to locate your phone if you have your wallet but lost your phone. I keep my wallet in my back pocket so at first I was worried that sitting down the pressure would cause the button to alert my phone every time I sat down. In the 3 months I’ve had this in my pocket I think it’s happened twice so it’s really not an issue in my opinion.<br>Now my only issue and it’s not major is the loudness of the speaker on the wallet. You can hear it even when it’s in the wallet but if it fell into a couch or under a bunch of blankets and you have a heavy or very thick wallet it could be hard to hear especially if you have bad hearing. It’s not a deal breaker honestly because it’s so low profile that it’s honestly better than losing your wallet and having nothing to help you and the benefit is that you can at least check the app and have a general idea where it is anyway which then you can activate the sound and between the two you can find it pretty easily. Just be aware that you’re not gonna have an air raid siren blasting out of your wallet.<br>Overall I’d recommend it. It’s an extra precaution that adds peace of mind. It’s easy to connect and easy to use.",
        "helpful" :23
    },
    {
        "id":28,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"Kosi onyeka",
        "date" :"Reviewed in the United States 🇺🇸 on December 14, 2022",
        "verified" :true,
        "comment" :"This is definitely necessary for me because I loose my wallet a lot. The issue is that sometimes it does not connect to my wallet even when it’s in close range. It sometimes makes me feel like I left/lost my wallet somewhere else but it really was just in my back back a few feet away. The connection should be a lot stronger than it is to avoid these false-positives situations.",
        "helpful" :3
    },
    {
        "id":29,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"Gordon Ewasiuk",
        "date" :"Reviewed in the United States 🇺🇸 on October 10, 2022",
        "verified" :true,
        "comment" :"",
        "helpful" :0
    },
    {
        "id":30,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"",
        "date" :"",
        "verified" :true,
        "comment" :"After losing my keys...then my wallet, I turned to Tile and Tile didn't disappoint! Tile's slim tracker fits into most wallets and you really forget it's there. It's so unobtrusive and just hangs out until you need it. I'm a heavier guy and that slim tracker has held up like a champ.<br><br>The keychain tracker fits onto most keychains and performs just as well. I attached mine to my keychain using a zip-tie for security. It has performed flawlessly. When my keys fell out of my pocket, I was able to track them, sound an alert, and find them again!<br><br>The \"sticker\" went on the back of my TV remote...which is always disappearing.<br><br>The Tile app is just incredibly easy to use. The ability to see the last known location of a Tile tracker makes it super easy to track down missing keys, wallet, or whatever. GPS with Google Maps is just awesome.<br><br>Tile has two premium plans that are worth exploring. Both plans have some pretty neat features like Smart Alerts - when you leave something behind, you get an alert! They also include a 30-day localtion history, warranty replacements of broken or damaged Tiles, exclusive Customer Care (7 days a week), and Item Reimbursement! If your Tiled item is lost and Tile can't find it, Tile will reimburse you. The Premium plans reimburses up to $100. The Premium Protect plan reimburses up to $1000.<br><br>I was showing off the Tile app and trackers to a family member and she immediately went to Amazon and bought the same kit!",
        "helpful" :26
    },
    {
        "id":31,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"S. Mcgovern",
        "date" :"Reviewed in the United Kingdom 🇬🇧 on May 12, 2022",
        "verified" :true,
        "comment" :"All four items that have tile attached showed & worked well? If I couldn’t find my keys press the tile symbol on my phone & it would ring the tile. The disappointment came when I couldn’t find my wallet which has the tile in it, it shows on the app my wallets last destination was my home address, so even though I couldn’t find my wallet & it wasn’t connected to tile I knew my wallet was in or around my house, I searched everywhere. Only to get a message from a lady who had found my wallet 30miles away, which was in the vicinity of where I had been working, if tile app had shown me this was the true last destination, I would have been able to retrace my steps. One very disappointed customer",
        "helpful" :9
    },
    {
        "id":32,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"hissing sid",
        "date" :"Reviewed in the United Kingdom 🇬🇧 on November 19, 2021",
        "verified" :true,
        "comment" :"I purchased the key one the 28 pound one that doesn't work like its big brother the tile slim. I mislaid my galaxy note ten plus this evening and I thought no problem ,all I have to do is double click the button on either device my phone will ring and as if by magic my phone would be found. But no I double clicked both devices several times while walking around my house trying to hear my phone ring. I went out onto my drive stood next to my car again total silence. However on looking inside the car I found my phone. Now the phone was in the central console and I was standing by the open door I tried both devices again nothing the phone didn't even murder vibrate or anything else. I picked up the phone and holding it in the same hand as both devices ,and when I clicked my phone rang. I don't see the point of spending out on these things if the first time you go to use it they don't work. So first thing in the morning I will be getting a jiffy bag and returning the useless things. My advice for anyone looking to be able to find your phone wallet or keys don't bother with this expensive rubbish, keep them in a day glow fluorescent bag you might look like a gimp but you won't loose them .",
        "helpful" :8
    },
    {
        "id":33,
        "forID": 6,
        "cat": "accessories",
        "image" :"",
        "name" :"BenG",
        "date" :"Reviewed in the United Kingdom 🇬🇧 on February 15, 2022",
        "verified" :true,
        "comment" :"I've had a Tile fob for a couple of years and it is a bit unreliable, but often saves me time when looking for keys. So after losing my wallet for days at a time last year I thought i'd grab a card for it. Again, it's not fantastic in terms of connection - seems that you only have to have a couple of walls between you and the phone for it to not find it - but if you walk around enough it'll pick up eventually. Just peace of mind really.<br><br>The biggest shame is that the most useful feature (your phone beeps when it loses connection with the fob/card) is a paid for subscription service.",
        "helpful" :7
    },
    {
        "id":34,
        "forID": 7,
        "cat": "accessories",
        "image" :"",
        "name" :"Jake fletcher",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"I use these in all 14 of my Tactacam Reveals as these are the specs they require and these cards work flawlessly! SD cards in general have a failure rate, but these SD cards havent let me down!",
        "helpful" :1
    },
    {
        "id":35,
        "forID": 7,
        "cat": "accessories",
        "image" :"",
        "name" :"Amazon Customer",
        "date" :"Reviewed in the United States 🇺🇸 on December 17, 2022",
        "verified" :true,
        "comment" :"I have gotten a dozen of these cards and NEVER had a problem at all with them! Great and a decent price too!",
        "helpful" :0
    },
    {
        "id":36,
        "forID": 7,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/92129bb5-12d6-44b5-8805-904b2bf9b631._CR0,0,375,375_SX48_.jpg",
        "name" :"Theodore N. Schnell",
        "date" :"Reviewed in the United States 🇺🇸 on December 13, 2022",
        "verified" :true,
        "comment" :"It does what I need it to do -- allows me to make and store images until I can download them onto my laptop for post-production work.",
        "helpful" :0
    },
    {
        "id":37,
        "forID": 7,
        "cat": "accessories",
        "image" :"",
        "name" :"Isaac W. Henry Jr.",
        "date" :"Reviewed in the United States 🇺🇸 on December 16, 2022",
        "verified" :true,
        "comment" :"I like to use this this SanDisk for weddings, because there is plenty of room for pictures and video.",
        "helpful" :0
    },
    {
        "id":38,
        "forID": 7,
        "cat": "accessories",
        "image" :"",
        "name" :"Sean",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"It's a nice fast card. I usually bought the cheapest card and buffered constantly. This card kept up with a few long bursts.",
        "helpful" :0
    },
    {
        "id":39,
        "forID": 8,
        "cat": "accessories",
        "image" :"",
        "name" :"Steven",
        "date" :"Reviewed in the United States 🇺🇸 on December 7, 2022",
        "verified" :true,
        "comment" :"First, I have several of these Belkin surge protectors and they work great. No complaints whatsoever. However, the latest one I purchased through Amazon warehouse was advertised as \"Like New\" and the item/carton was far from that. The carton was torn to shreds and just in terrible shape. The prongs on the actual surge protector were all pointed to the right like it had been stepped on or something similar. I am very disappointed in what Amazon considers \"Like New\" after this experience. I was able to bend back the prongs and get the surge protector plugged in but I wonder if the prongs are weaker than usual because of being bent in one direction and back the other way. Please try & do a better job of checking the worn merchandise at Amazon going forward so future customers are not so disappointed.",
        "helpful" :1
    },
    {
        "id":40,
        "forID": 8,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/15e47425-0ab3-49e7-9a88-6688dff08b84._CR1,0,335,335_SX48_.jpg",
        "name" :"mikecart1",
        "date" :"Reviewed in the United States 🇺🇸 on December 16, 2022",
        "verified" :true,
        "comment" :"Never had an issue with any type of surge protector in my life. My issues come down to having electronics not connected to one during a lightning storm and finding out later my computer motherboard or something else is fried and/or destroyed. Definitely a solid investment if you care about your TVs, computers, or other high-end electronics. Lots of connectors on these and shaped in a way that they can fit inside bookcases or along the floor as most people would have them.",
        "helpful" :0
    },
    {
        "id":41,
        "forID": 8,
        "cat": "accessories",
        "image" :"",
        "name" :"OrangeFan",
        "date" :"Reviewed in the United States 🇺🇸 on December 2, 2022",
        "verified" :true,
        "comment" :"Replaced my old surge protector with this Belkin model at a great price. 12 outlets and I was able to mount it on the rear lower panel of my computer desk instead of laying on the bottom shelf like the old one was. As mentioned in some reviews, the mounting holes are small and you'll need small screws which you can find at any hardware/home improvement store. Results were not such a dusty tangled mess of cords laying all over the shelf. That said, bottom line is hoping that it gives me the protection I need.",
        "helpful" :1
    },
    {
        "id":42,
        "forID": 8,
        "cat": "accessories",
        "image" :"",
        "name" :"Maryssa P.",
        "date" :"Reviewed in the United States 🇺🇸 on November 24, 2022",
        "verified" :true,
        "comment" :"This power strip/surge protector just saved us thousands!! A car hit a telephone pole on our grid yesterday and left several streets without power and with fried/burned meter boxes. We lost a few minor electronics that were plugged in and our Xbox One which was plugged directly into the wall, but this surge protector saved the rest of our gaming systems and our TV/sound system. Cannot recommend it highly enough! There was A LOT plugged into it too, since it has so many outlets. I just ordered a replacement AND a backup!",
        "helpful" :5
    },
    {
        "id":43,
        "forID": 8,
        "cat": "accessories",
        "image" :"",
        "name" :"Monsterlilly",
        "date" :"Reviewed in the United States 🇺🇸 on December 15, 2022",
        "verified" :true,
        "comment" :"Like: the price is great. Works good. Feels quality more than the other cheap ones for $20<br>Dislike: not much to dislike. Maybe the coord should be longer but that’s my only complaint",
        "helpful" :0
    },
    {
        "id":44,
        "forID": 8,
        "cat": "accessories",
        "image" :"",
        "name" :"cannabible customer",
        "date" :"Reviewed in the United States 🇺🇸 on November 8, 2022",
        "verified" :true,
        "comment" :"It's a surge protector and large power strip. It works as a power strip. It's nice that outlets are spaced out to accommodate large plugs, which is quite common.<br>I can't tell for sure if it works as a surge protector. I've had a power outage recently and when things came back on, nothing plugged up to this got fried. Maybe there was no surge to begin with. Maybe there was & this worked great. I'd know if there was a surge if stuff got fried, and in that case, I'd know this did not work as advertised. The fact that nothing notable happened is a good thing.",
        "helpful" :3
    },
    {
        "id":45,
        "forID": 9,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/60270af1-0b89-4d37-b94d-69388ebf4a74._CR62,0,375,375_SX48_.jpg",
        "name" :"Matthew",
        "date" :"Reviewed in the United States 🇺🇸 on November 23, 2022",
        "verified" :true,
        "comment" :"This is a very good headset in important ways:<br>- sound quality<br>- build quality<br>- comfort<br>- ease of pairing/remembering/connecting with PC<br><br>However, for the price point and rave reviews, I am VERY disappointed in:<br><br><br>- The useless BlueParrot button (it's \"programmable\" with the app -- yeah, an app -- that doesn't work). There are four buttons on this headset: volume up, volume down, power, and BP button. 25% of your buttons are useless. Why isn't that button a hard-wired \"pair\" button, or pause, or switch devices, or ANYTHING useful?<br>- The spotty connection quality. I walk around my house, never more than 10M from my PC, and half the time my music cuts in and out like I'm on knockoff earbuds from 2014. For more than a Benjamin, that's dumb.<br>- The lack of swapping between devices. After about a month, this headset just flat stopped being able to pair with my phone. Swapping seamlessly from Device 1 to Device 2 was part of the point of researching and buying this model, and it sucks at it.<br><br>Overall, four stars instead of three or even two ($130 for music that cuts in and out?! Really!?) because, when it does work, the headset is amazing.",
        "helpful" :15
    },
    {
        "id":46,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"Anthony p.",
        "date" :"Reviewed in the United States 🇺🇸 on December 11, 2022",
        "verified" :true,
        "comment" :"I have had multiple versions of blue parrot headsets. I definitely like this one. My only complaint is how the band fits my head. It’s a little tight and if you slide it down a notch it’s way to loose. I liked my b250 a little better bc of the metal band. It definitely fit my head better. But as far as controls, sound quality, and overall experience, it’s perfect. Can still have a conv at the back of a 53’ trailer while my phone is still in the truck",
        "helpful" :1
    },
    {
        "id":47,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"Amazon Ron",
        "date" :"Reviewed in the United States 🇺🇸 on December 14, 2022",
        "verified" :true,
        "comment" :"Some of my older friends had trouble hearing me when I was using standard Bluetooth headphones in the car. The background noise somehow got through, even with noise cancelling.br><br>So, I went to the Mac Daddy of headsets, the BlueParrott B350-XT. It is absolutely stellar. Everyone, so far, compliments how clear the sound is. Love the boom microphone which I can position perfectly near my mouth. And, on my end, the sound quality is just as good from a clarity standpoint.<br><br>Outstanding purchase! Should have bought this years ago.",
        "helpful" :0
    },
    {
        "id":48,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"Alec Applebaum",
        "date" :"Reviewed in the United States 🇺🇸 on November 30, 2022",
        "verified" :true,
        "comment" :"I was comparing this headset to the Plantronics Voyager which I have owned and used for the last 4 years. The Voyager is a fantastic headset with the only real negative being how long it lasts on a charge and being that I'm a heavy phone user this is an issue for me. As far as Blueparrot goes, I have never come close to running out of juice. It's fantastic. As for the sound quality I think it's a bit better/louder than the Voyager. Now as for call quality I had someone I trust on the other end of the call to test this out because, if the call quality isn't good, battery life and volume doesn't matter. The consensus was the Voyager sounded a bit better but barely so. The BlueParrot still sounded good. The bottom line is if you're looking for a great bluetooth headset look no further.",
        "helpful" :7
    },
    {
        "id":49,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"Elvee",
        "date" :"Reviewed in the United States 🇺🇸 on October 5, 2022",
        "verified" :true,
        "comment" :"So I bought this headset back in February. I used it great until September. I'm a truck driver, so daily use with my iPhone. Audio books, podcasts, phone calls, Siri, etc. It has a great range, I can even walk all the way around my truck and not drop a call with my phone in the cab. Then one day - nada. Won't charge, can't connect to my phone. The red light stayed on like it was charging, but nothing. So, I called the company. I've been a driver a long time, and I've had my fair share of junk - when it fails no one talks to you, no refund, no warranty service, and tbh, that's what I was expecting.<br>Blue Parrot stood behind the product, and after a short trouble shooting phone call with a polite technician, they just mailed me a new one. I didn't even have to send the old one back. I got a brand new headset from them with very little hassle. Its so rare to find that kind of customer service anymore. Thanks Blue Parrot!<br>I love the volume, the noise cancelling is very good and battery life is over 11 hours per full charge. I can even use it with Siri! My hubby bought one, too, in March and his is still working great.",
        "helpful" :31
    },
    {
        "id":50,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"Gorby",
        "date" :"Reviewed in the United States 🇺🇸 on November 15, 2022",
        "verified" :true,
        "comment" :"I have been using Plantronics legend and 5200 for years but each of them starts losing Bluetooth connection to my Samsung phones after a while so I decided to try the BlueParrott.<br>GOOD: fits well, Bluetooth connection is good for both regular and WhatsApp calls. My friends hear me clearer this time. Battery lasts long. Uses USB-C charger which is common.<br>BAD/CONS: Does not announce battery life. Software is too simple and lacks a lot. speaker sound not as good as the legend, this sounds lighter.",
        "helpful" :8
    },
    {
        "id":51,
        "forID": 9,
        "cat": "accessories",
        "image" :"",
        "name" :"John Pestle",
        "date" :"Reviewed in the United States 🇺🇸 on September 28, 2022",
        "verified" :true,
        "comment" :"Excellent stereo headset. I am a lawyer who telecommutes 100% of the time. Particularly during COVID, I noticed that I had better, less tiring and easier comprehension on phone/Zoom calls when I used my Apple earbuds - - because I was using both ears. As opposed to my then phone operator style single ear Blue Parrot headset. Our brains comprehend best when we hear with both ears!<br><br>So I then bought these (only two ear version I could then find of Blue Parrot) and have been very pleased, in fact have bought three of them (for two locations and to replace one I broke).<br><br>Bottom line is I hear extremely well with these, and adjacent noise (children) does not come through. I have recommended them highly to business acquaintances who have been similarly impressed.<br><br>Comments: If you don’t flip the mike boom down towards your lips folks can’t hear you. That’s why they are called noise cancelling! They emphasize bass frequencies more than mid-range (which is where the intelligence in speech comes in). So people’s voices sound lower than they do in person - - Once dealing with a CSR with a very deep voice I had to switch back to my earbuds. Have not tried the app or tried to program them, work fine out of the box. Have not used them with music, in part due to the high bass, but that is not what I bought them for. Long battery life. Large and comfortable, size is why I bought a second one to use at our daughters (largish for travel, esp if you are traveling carry-on). Be gentle with the on-off switch, which is what I broke after three years.<br><br>Highly recommend these.",
        "helpful" :13
    },
    {
        "id":52,
        "forID": 10,
        "cat": "accessories",
        "image" :"",
        "name" :"Alex",
        "date" :"Reviewed in the United States 🇺🇸 on December 15, 2022",
        "verified" :true,
        "comment" :"I love this, everything about it. It works just as advertised and the magnetic connection is strong enough that you can expand the popsocket and collapse it easily. The magnetic connection is VERY strong but as long as you have even a little bit of hand strength you should be fine.<br>BUT BE WARNED:<br>If you want to use it on top of a case, MAKE SURE THE CASE IS MADE TO SUPPORT MAGSAFE.<br>If it's not, the case will prevent the popsocket from working properly. Any case that isn't made to support magsafe will be like a wall between your phone and the popsocket, which will cause the popsocket to get pulled off every time you try to expand it. I bought a case from the company \"Mous\" and it works perfectly with the popsocket.",
        "helpful" :2
    },
    {
        "id":53,
        "forID": 10,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/fd304966-939e-40b5-b379-ef78d9c27ee4._CR0,0.0,333,333_SX48_.jpg",
        "name" :"Storm2580",
        "date" :"Reviewed in the United States 🇺🇸 on December 8, 2022",
        "verified" :true,
        "comment" :"I'm impressed. My wife has used adhesive PopSockets in the past, and depending on the phone case, they might or might not adhere well. This is why I never bought one previously. However, when I saw this, I figured it was worth a shot, since I have an OtterBox MagSafe case. To get to the point, it's great. It holds very strongly to the case, but not so strongly that you can't take it off when you want to use a wireless charger. Now I can hold my phone more easily, and I have a kickstand to use while watching videos.",
        "helpful" :4
    },
    {
        "id":54,
        "forID": 10,
        "cat": "accessories",
        "image" :"",
        "name" :"Rae Zemi",
        "date" :"Reviewed in the United States 🇺🇸 on December 15, 2022",
        "verified" :true,
        "comment" :"Easy to magnetically attach to my phone with the Apple silicone case on, and easy to remove for wireless charging. It’s also sturdy & secure when holding my 14 Pro Max in one hand, and the marble pattern is super cute! 10x better than the pop-slide I used to have.<br>An added bonus (for me) is not having any logo & hiding the apple logo on the back of my case. 💜 I don’t like branding.",
        "helpful" :1
    },
    {
        "id":55,
        "forID": 10,
        "cat": "accessories",
        "image" :"",
        "name" :"AnkurWat",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"I like the idea of Popsockets but I wanted a MagSafe design so I can remove it, and then use other accessories like my portable Anker MagSafe charger. Also I like taking off the pop socket when I put it in my car’s phone mount.",
        "helpful" :3
    },
    {
        "id":56,
        "forID": 10,
        "cat": "accessories",
        "image" :"",
        "name" :"Jun Z",
        "date" :"Reviewed in the United States 🇺🇸 on November 17, 2022",
        "verified" :true,
        "comment" :"UPDATE 12/4/22: I gave this another shot since I wanted a quality pop socket and it was on sale for Cyber Monday. The product no longer comes with that annoying sticker, or at least this time it didn't come with it. If it doesn't come with that sticker then its a 5/5.",
        "helpful" :8
    },
    {
        "id":57,
        "forID": 10,
        "cat": "accessories",
        "image" :"",
        "name" :"Amazon Customer",
        "date" :"Reviewed in the United States 🇺🇸 on December 16, 2022",
        "verified" :true,
        "comment" :"I wasn’t sold on the mag-sage products until I saw this! I love how pop sockets make it so easy to hold your phone or prop it up to watch a video, and this mag-safe one is amazing! Easy to pop on and off, stays on well. Would recommend!",
        "helpful" :0
    },
    {
        "id":58,
        "forID": 11,
        "cat": "accessories",
        "image" :"",
        "name" :"Ana",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"I got this headset because I wanted a wireless headset that had the option to connect to a device using an aux cord. I usually use this at home and at the gym, and I plan to use it when I travel by plane (I had an experience where the wireless headset I had at the time did not connect with Bluetooth during the flight, so I really wanted a headset that came with an optional aux cord). This device does not have a noise cancelling feature, but it does block out most noises I encounter fairly well. I have had no issues with this device so far, so I would say it is a decent device for $70-$80.",
        "helpful" :0
    },
    {
        "id":59,
        "forID": 11,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/e70978ea-9a49-4b4a-a545-17b0e36c2857._CR0,0.0,333,333_SX48_.jpg",
        "name" :"Jason Angulo",
        "date" :"Reviewed in the United States 🇺🇸 on December 12, 2022",
        "verified" :true,
        "comment" :"Really enjoying this, I use them for hours on end while doing my homework and don’t get any discomfort even with my glasses. Ear pads are super soft like memory foam. Sound quality is great especially when you connect with the audio jack, crisp and good base. If you can swing the Crusher Evo I hear those sound better but for the price you cnet beat these.",
        "helpful" :0
    },
    {
        "id":60,
        "forID": 11,
        "cat": "accessories",
        "image" :"https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/ac25c917-e71f-4f4f-ace3-00bddf32b9a8._CR0,0,500,500_SX48_.jpg",
        "name" :"Lou",
        "date" :"Reviewed in the United States 🇺🇸 on December 16, 2022",
        "verified" :true,
        "comment" :"The sound is pretty impressive for the cost. It was a nice introduction to wireless over the ear headphones. The size however is snug for me. It might be that I have a big head or that these are designed for little headed people. Not sure but at max extension it just fits over my head. Do with that information as you wish.",
        "helpful" :0
    },
    {
        "id":61,
        "forID": 11,
        "cat": "accessories",
        "image" :"",
        "name" :"Delany Davis",
        "date" :"Reviewed in the United States 🇺🇸 on December 10, 2022",
        "verified" :true,
        "comment" :"Nothing too bad going on with the product so far. The only thing is that it has recently started to disconnect from my phone when I I try to connect them. It only does this the first time, but this issue i mildly annoying. It worked fine for the first 3 months then this issue popped up. After connecting the headphones they work just fine and like normal. So not a bad product so far",
        "helpful" :0
    },
    {
        "id":62,
        "forID": 11,
        "cat": "accessories",
        "image" :"",
        "name" :"HalloweenQueen",
        "date" :"Reviewed in the United States 🇺🇸 on November 16, 2022",
        "verified" :true,
        "comment" :"Because the part with the actual speakers is able to turn 180 degrees, theres like a little screw part, right? When I wear the headphones, little strands of my hair get caught in those parts and eventually get yanked out of my head when I take move them LMAO It's not that big of a deal, but it's worth mentioning",
        "helpful" :14
    },
    {
        "id":63,
        "forID": 11,
        "cat": "accessories",
        "image" :"",
        "name" :"Fernando Soria",
        "date" :"Reviewed in the United States 🇺🇸 on December 5, 2022",
        "verified" :true,
        "comment" :"Sound quality is good but they’re not very loud and the bass doesn’t hit like skull candy typically does",
        "helpful" :0
    },

]

